1.2.1
portworx/terraform-ibm-portworx-enterprise pull request #49
Opened 2022-12-14 11:32 UTC by Glitchfix

What this PR does / why we need it:
PX-Terraform IBM - Scaling up storage nodes using TF, related to "max_storage_nodes_per_zone"

Which issue(s) this PR fixes (optional)
Closes #[PWX-27839](https://portworx.atlassian.net/browse/PWX-27839)

Special notes for your reviewer:
this PR contains code for autopilot installation code but is not part of this PR as more improvement on autopilot rules is required

2022-12-15 09:07 UTC, vinayakshnd requested changes
@Glitchfix pls remove autopilot related changes from this branch. Mergeing this branch will make feature available to users without testing. File a separate PR for autopilot

2022-12-15 09:13 UTC, vinayakshnd commented on utils/portworx_configure_max_storage_node_per_zone.sh
> +    printf "[ERROR] Helm couldn't find Portworx Installation, will not proceed with the upgrade!! Please install portworx and then try to upgrade.\n"
Change above ERROR msg.
```suggestion
    printf "[ERROR] Helm couldn't find Portworx Installation, will not proceed with configuring max storage nodes per zone!!\n"
```

2022-12-15 09:14 UTC, vinayakshnd commented on utils/portworx_configure_max_storage_node_per_zone.sh
> +    printf "[ERROR] Portworx Storage Cluster Not Found, will not proceed with the upgrade!! Please install Portworx Enterprise and then try to upgrade.\n"
Same as above. Change error msg.

2022-12-15 09:14 UTC, vinayakshnd commented on utils/portworx_configure_max_storage_node_per_zone.sh
> +        printf "[ERROR] Portworx Storage Cluster is not Online. Cluster Status: ($STATUS), will not proceed with the upgrade!!\n"
Same here

2022-12-15 09:25 UTC, vinayakshnd requested changes

2022-12-15 09:25 UTC, vinayakshnd commented on utils/portworx_configure_max_storage_node_per_zone.sh
> +    printf "[ERROR] Failed to Upgrade!!\n"
Upgrade refers to PX version upgrade. Replace `upgrade` keyword everywhere in the file with `configure maxStorageNodesPerZone`.

2022-12-16 05:43 UTC, Glitchfix commented
> @Glitchfix pls remove autopilot related changes from this branch. Mergeing this branch will make feature available to users without testing. File a separate PR for autopilot

the autopilot changes won't be triggered unless there is a flag set for it as the deffault value for it false

2022-12-16 06:28 UTC, vinayakshnd commented
@Glitchfix if there is variable/flag for enabling the autopilot then user can enable it. We can not prevent user from setting that flag.

2022-12-16 08:39 UTC, vinayakshnd approved these changes
LGTM

2022-12-16 08:41 UTC, merged